### ISSUE TITLE
Values exported to `env` independent of `export_to_envs`

### ISSUE THREAD

**Issue by charlesbluca** [the-coding-turtle/ga-yaml-parser#40]
When using the latest version of this action, I notice that even when `export_to_envs` is left at its default value of `false`, the parsed values are still exported to the GitHub `env`.

As an example, here is a workflow using this action; note the configuration of this action under the "Parse current axis YAML" step, and the resulting `env` in all subsequent steps:

https://github.com/dask-contrib/dask-sql/runs/6087646909?check_suite_focus=true

**Comment by the-coding-turtle** [comment]
Hi @charlesbluca ,

Thanks for the hint. I have fixed the bug. 
The reason was, that the input variables are always strings and not boolean. But i used this strings as boolean. Resulting in always true for the string "false" and "true".

I hope everything is working now. Let me know if you encounter some other errors.
